### ISSUE TITLE
Empty user list

### ISSUE THREAD

**Issue by hypervtechnics** [crobibero/Jellyfin.Plugins.Gotify#10]
I am on Jellyfin Version 10.4.1 and can't see any entries in the user list. I only have one user.

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-web/issues/517
Currently a bug in jellyfin-web, try the steps from this issue

**Comment by hypervtechnics** [comment]
The steps worked. Thank you! :)
